version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Insider1GizliSifre*
      MYSQL_DATABASE: insider_db
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Insider1GizliSifre*
      - DB_NAME=insider_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge